apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: web-app-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops-webapp
    repoURL: https://github.com/amitkesarkar29/ocp-gitops-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
